### ISSUE TITLE
Escelator performance

### ISSUE THREAD

**Issue by Noaaan** [jonafanho/Minecraft-Transit-Railway#11]
**Behaviour**
Currently the escelator creates a large amount of lag whenever you step on it. Having multiple entities creates too many updates. It needs to be optimized.

**Reproduction Steps**
Place an escalator down and open up the performance debug screen (ALT+F3)
Watch the lag display spike when you step on an escelator.

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods: 3.0.0

**Comment by jonafanho** [comment]
Hello, do you have other mods installed? How much RAM did you allocate to Minecraft?

**Comment by BoscoChung1234** [comment]
> Hello, do you have other mods installed? How much RAM did you allocate to Minecraft?

Hello, it shouldn't be a RAM problem. Tried on Fabric with Optifine installed, when riding on escalator it causes FPS drop. PC has Nvidia GT730, i5-7400, 16GB DDR4. Doing anything except using escalator does not cause FPS drop, because I tried summoning a hundred of tnt explosions, it did not drop at all, maybe a code problem.

**Comment by RDKRACZ** [comment]
@BoscoChung1234 why do you use optifine with fabric? Cuz shaders?

**Comment by BoscoChung1234** [comment]
> @BoscoChung1234 why do you use optifine with fabric? Cuz shaders?

cuz Canvas has light glitches and sodium does not work
