### ISSUE TITLE
Rails hit performance

### ISSUE THREAD

**Issue by Aviator737** [jonafanho/Minecraft-Transit-Railway#353]
Rails hit performance.

**Reproduction Steps**

1. Place some rails.

**Screenshots**
FPS with rails:
![2022-05-03_16 50 25](https://user-images.githubusercontent.com/6958547/166461101-dcb06afe-4c06-4d09-8ed6-1a69dce3e89a.png)
FPS in same village without rails:
![2022-05-03_16 50 54](https://user-images.githubusercontent.com/6958547/166461156-d7f9eabc-7ea2-40c8-86a9-094857c34058.png)

**Environment**

- Minecraft Version: 1.16.5
- Installed Mods:  
OptiFine_1.16.5_HD_U_G8_MOD (shaders: ComplementaryShaders_v4.3.3)
architectury-1.31.60
MTR-forge-1.16.5-3.0.0

**Additional Information**
I've tried Immersive railroading mod and I'm getting better fps with much more complex models.
![2022-05-03_17 19 30](https://user-images.githubusercontent.com/6958547/166461752-4a2fd3f9-516d-484e-a75f-408f1c6bd6a0.png)

**Comment by HistoryButtsandCo10** [comment]
Thanks for giving time and sharing your critiques of the mod,  

the mod itself is actually more of automated transportation, in the basis of creating or recreating complex transit systems in your world. Online you'll see the mod used in lieu with cities, towns, etc. In addition to rendering trains, they take a great lot when it comes to fps - from pathfinding to the usage of the dashboard in particular; rather than having just plain rails in general. Though our models are slowly getting more complex, and each of our trains took time and effort when it comes to modelling and rendering; it's a good balance of quality and for it to render properly and with ease in-game. Appreciate your perceptive account of our mod, and if the mod is not for you; suggest looking for other train mods that fit your liking. Thanks!

**Comment by DumbSharkGura** [comment]
The length of the rails between the 2 mods aren't even the same, of course there'll be performance difference. Learn how to conduct a fair experiment before even trying to rant and hate MTR Mod here. In the end, you're just baised towards IR, and I'd suggest you go and play IR instead. You're more than welcome to give valuable comments and raise issues, but not like these which are clearly biased and unfair when doing comparisons.

**Comment by zbx1425** [comment]
Rails do hit performance.
That's due to a fundamental difference in how it's implemented in MTR and IR, and some quite technical thing of how the Minecraft rendering system works. i.e. it's not simple problem and there's no easy fix on this.
There are ways to optimize this, but that might not be implemented very soon, as it requires major work on the rendering routine.

**Comment by Aviator737** [comment]
I’m sorry if I seemed biased, I was just reporting that the problem exists. Thanks guys for such a cool mod, there are no alternatives. I thought it would be useful to specify another mod in order for developers to see how it is done in other mods.

**Comment by kettle-7** [comment]
you could test fairly :~)

**Comment by kettle-7** [comment]
put two curves of the same radius, one of each mod

**Comment by kettle-7** [comment]
wait 10 seconds after placing each, then average the framerate over the next 10 seconds

**Comment by HistoryButtsandCo10** [comment]
> I’m sorry if I seemed biased, I was just reporting that the problem exists. Thanks guys for such a cool mod, there are no alternatives. I thought it would be useful to specify another mod in order for developers to see how it is done in other mods.

No, it's alright. Any sort of help and developments or critiques in particular is appreciated, especially from an outsider perspective. Feel free to join our discord server if you have any more questions or inquires regarding our mod.  Thank you again!

**Comment by Aviator737** [comment]
> you could test fairly :~)

In fact, the length was about the same, but that's not even the point, but the difference between the models and their effect on FPS. I also placed a train from IR for more impact.

**Comment by jonafanho** [comment]
Related to #125

**Comment by kettle-7** [comment]
Nemo's Transit Expansion's 3D rails seem to be better on performance
