### ISSUE TITLE
Passanger NPC

### ISSUE THREAD

**Issue by Steve-xmh** [jonafanho/Minecraft-Transit-Railway#377]
Can we have passanger NPC that can get on and off trains to travel between stations? I think that can rich our traveling experience.

**Comment by kettle-7** [comment]
This has been suggested so many times, and the answer isn't gonna change soon, the way the trains work means entities that aren't players can't ride the train, because instead of the server moving anybody on the train, the client moves the player. This stops the jittering people have been complaining about, but it can't work with npcs.

**Comment by XHG78999** [comment]
> Can we have passanger NPC that can get on and off trains to travel between stations? I think that can rich our traveling experience.

You can use some other NPC mods extended to make these effects.

**Comment by XHG78999** [comment]
> > Can we have passanger NPC that can get on and off trains to travel between stations? I think that can rich our traveling experience.
> 
> You can use some other NPC mods extended to make these effects. 

Also, like as the video of KaMuaMua, You can use addition on server to make 'fake' players. They have AI, and can do anything by player, even like vape or other cheats.

**Comment by jonafanho** [comment]
Related to #307
