### ISSUE TITLE
I would like to be able to sit in a train chair.

### ISSUE THREAD

**Issue by mull1111** [jonafanho/Minecraft-Transit-Railway#582]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to sit on the train.
You can use the shift key to crouch down, but that is all.
Also, sometimes you get swung off the train with it, so I don't want to use it.

**Describe the solution you'd like**
Like realtrainmod, you should be able to sit tight on the train.
However, if you can't stand up after sitting down, it is meaningless (in the case of realtrainmod, the moment you press the shift key, you will be shaken off.) I thought it would be better to right-click to sit down, and press the shift key to stand up.
Forced disembarkation should be the same as before.

**Comment by 52PD** [comment]
OK, based on how Minecraft Transit Railway works, this is impossible.

Since train model in the mod are not collision box(just some stiker-like images), the only way to make you move on the train is forcing you moving when train moving (if you use third-person camera, you will see you are actually “running” on the train, not standing).

Translate by Google:
Minecraft Transit Railway の仕組みからすると、これは不可能です。

mod の列車モデルは衝突ボックスではありません (ステッカーのような画像のみ) ので、列車で移動させる唯一の方法は、列車が動いているときに強制的に移動させることです (三人称カメラを使用している場合は、 立っているのではなく、実際に電車で「走っている」)。

**Comment by mull1111** [comment]
I understand. It's a matter of specifications.
I will delete the post.
Thank you.
