### ISSUE TITLE
Announcements 

### ISSUE THREAD

**Issue by Sophiapinkcutie** [jonafanho/Minecraft-Transit-Railway#690]
I can't play Chinese announcement on my world and I've tried everything I could and the mod still can't play the Chinese announcement. Please try to fix it thanks! if it's something to do with my Minecraft then please tell me how to fix it thanks!

**Comment by kettle-7** [comment]
It's because of windows settings, you have to use control panel (windows <= 10) or settings (windows >= 11)
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/64388266/2f5e8a21-17b0-4906-bb56-c106a02746eb)
![image](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/64388266/87b30ada-d1d8-4cbc-8a00-d7b4577935a2)

**Comment by Sophiapinkcutie** [comment]
I've tried that. it still doesnt work!
